name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Semantic release type (major, minor, or patch)'
        required: true
        default: 'patch'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Configure git user
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Bump version
      run: |
        npm version ${{ github.event.inputs.releaseType }}
        git push --follow-tags

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}